#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

function mapDir(dir, indent = 0) {
  if (!fs.existsSync(dir)) return "";
  const prefix = "  ".repeat(indent);
  return fs.readdirSync(dir, { withFileTypes: true })
    .filter(i => !i.name.startsWith(".") && i.name !== "node_modules")
    .map(item => item.isDirectory()
      ? `${prefix}${item.name}/\n${mapDir(path.join(dir, item.name), indent + 1)}`
      : `${prefix}${item.name}`)
    .join("\n");
}

function countComponents(baseDir = process.cwd()) {
  const d = path.join(baseDir, "src", "components");
  if (!fs.existsSync(d)) return 0;
  return fs.readdirSync(d, { withFileTypes: true }).filter(i => i.isDirectory()).length;
}

function countTests(dir) {
  if (!fs.existsSync(dir)) return 0;
  let n = 0;
  for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
    if (item.isDirectory()) n += countTests(path.join(dir, item.name));
    else if (item.name.match(/\.test\.(tsx?|jsx?)$/)) n++;
  }
  return n;
}

function buildReadme({ projectName, problemStatement, stack, srcTree, componentCount, testCount, decisions, today }) {
  return `# ${projectName}

> Last generated: ${today}

## Problem Statement

${problemStatement || "_Fill in from your take-home prompt._"}

## Quick Start

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).

## Stack

${stack}

## Project Structure

\`\`\`
${srcTree}
\`\`\`

**${componentCount} component${componentCount !== 1 ? "s" : ""}** · **${testCount} test file${testCount !== 1 ? "s" : ""}**

## Scripts

| Command | Description |
|---|---|
| \`npm run dev\` | Start dev server |
| \`npm run build\` | Production build |
| \`npm run test\` | Run test suite |
| \`npm run type-check\` | TypeScript check |
| \`npm run lint\` | ESLint |
| \`node scripts/generate-component.js Name\` | Scaffold a component |
| \`node scripts/generate-readme.js\` | Refresh this README |

## Architecture Decisions

${decisions}

Full reasoning in [DECISIONS.md](./DECISIONS.md).

## CI

GitHub Actions runs on every push and pull request to \`main\`:

- **lint** · **type-check** · **test** (parallel jobs)

See \`.github/workflows/ci.yml\`.

## Trade-offs & What I'd Do Next

_Fill this in before submitting._

- [ ] Add Storybook or \`/design-system\` route for component docs
- [ ] Add E2E tests with Playwright for critical flows
- [ ] Add error boundaries per route segment

## Environment Variables

Copy \`.env.example\` to \`.env.local\`. Never commit \`.env.local\`.

---

_README generated by \`scripts/generate-readme.js\` — run "📝 Refresh README" task to update._
`;
}

if (require.main === module) {
  const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
  const projectName = pkg.name.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
  const problemStatement = pkg.description || "";

  let decisions = "_See DECISIONS.md_";
  if (fs.existsSync("DECISIONS.md")) {
    const raw = fs.readFileSync("DECISIONS.md", "utf8");
    const titles = [...raw.matchAll(/^## (ADR-\d+: .+)$/gm)].map(m => `- ${m[1]}`);
    if (titles.length) decisions = titles.join("\n");
  }

  const srcTree = mapDir("src");
  const componentCount = countComponents(process.cwd());
  const testCount = countTests("src");
  const today = new Date().toISOString().split("T")[0];
  const deps = { ...pkg.dependencies, ...pkg.devDependencies };
  const stack = [
    deps.next && `Next.js ${deps.next.replace(/[\^~]/, "")}`,
    deps.react && `React ${deps.react.replace(/[\^~]/, "")}`,
    deps.typescript && `TypeScript ${deps.typescript.replace(/[\^~]/, "")}`,
    deps.tailwindcss && "Tailwind CSS",
    deps.jest && "Jest + React Testing Library",
  ].filter(Boolean).join(" · ");

  const readme = buildReadme({ projectName, problemStatement, stack, srcTree, componentCount, testCount, decisions, today });
  fs.writeFileSync("README.md", readme, "utf8");
  console.log("✓ README.md updated");
}

module.exports = { mapDir, countComponents, countTests, buildReadme };
